-- booking_time_slot 时间槽表
CREATE TABLE IF NOT EXISTS `booking_time_slot` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `schedule_id` bigint NOT NULL COMMENT '排班编号',
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `slot_date` date NOT NULL COMMENT '日期',
    `start_time` time NOT NULL COMMENT '开始时间',
    `end_time` time NOT NULL COMMENT '结束时间',
    `duration` int NOT NULL DEFAULT 60 COMMENT '时长（分钟）',
    `is_offpeak` bit NOT NULL DEFAULT FALSE COMMENT '是否闲时',
    `offpeak_price` int DEFAULT NULL COMMENT '闲时价格（分）',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0可预约 1已锁定 2已预约 3已完成 4已取消',
    `lock_expire_time` timestamp DEFAULT NULL COMMENT '锁定过期时间',
    `lock_user_id` bigint DEFAULT NULL COMMENT '锁定用户编号',
    `booking_order_id` bigint DEFAULT NULL COMMENT '预约订单编号',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '时间槽表';

-- booking_order 预约订单表
CREATE TABLE IF NOT EXISTS `booking_order` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `order_no` varchar(64) NOT NULL COMMENT '预约订单号',
    `user_id` bigint NOT NULL COMMENT '用户编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `time_slot_id` bigint NOT NULL COMMENT '时间槽编号',
    `spu_id` bigint DEFAULT NULL COMMENT '服务商品SPU编号',
    `sku_id` bigint DEFAULT NULL COMMENT '服务商品SKU编号',
    `service_name` varchar(128) DEFAULT NULL COMMENT '服务名称',
    `service_pic` varchar(256) DEFAULT NULL COMMENT '服务图片',
    `booking_date` date NOT NULL COMMENT '预约日期',
    `booking_start_time` time NOT NULL COMMENT '预约开始时间',
    `booking_end_time` time NOT NULL COMMENT '预约结束时间',
    `duration` int NOT NULL DEFAULT 60 COMMENT '服务时长（分钟）',
    `original_price` int NOT NULL DEFAULT 0 COMMENT '原价（分）',
    `discount_price` int NOT NULL DEFAULT 0 COMMENT '优惠金额（分）',
    `pay_price` int NOT NULL DEFAULT 0 COMMENT '实付金额（分）',
    `is_offpeak` bit NOT NULL DEFAULT FALSE COMMENT '是否闲时优惠',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '订单状态：0待支付 1已支付 2服务中 3已完成 4已取消 5已退款',
    `pay_order_id` bigint DEFAULT NULL COMMENT '支付订单编号',
    `pay_time` timestamp DEFAULT NULL COMMENT '支付时间',
    `service_start_time` timestamp DEFAULT NULL COMMENT '服务开始时间',
    `service_end_time` timestamp DEFAULT NULL COMMENT '服务结束时间',
    `cancel_time` timestamp DEFAULT NULL COMMENT '取消时间',
    `cancel_reason` varchar(256) DEFAULT NULL COMMENT '取消原因',
    `user_remark` varchar(256) DEFAULT NULL COMMENT '用户备注',
    `merchant_remark` varchar(256) DEFAULT NULL COMMENT '商家备注',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '预约订单表';

-- booking_technician 技师表
CREATE TABLE IF NOT EXISTS `booking_technician` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `name` varchar(64) NOT NULL COMMENT '技师姓名',
    `avatar` varchar(256) DEFAULT NULL COMMENT '头像',
    `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
    `level` tinyint NOT NULL DEFAULT 1 COMMENT '技师等级',
    `intro` varchar(512) DEFAULT NULL COMMENT '简介',
    `specialties` varchar(256) DEFAULT NULL COMMENT '擅长项目',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0启用 1禁用',
    `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师表';

-- booking_technician_schedule 技师排班表
CREATE TABLE IF NOT EXISTS `booking_technician_schedule` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `schedule_date` date NOT NULL COMMENT '排班日期',
    `start_time` time NOT NULL COMMENT '开始时间',
    `end_time` time NOT NULL COMMENT '结束时间',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0正常 1请假',
    `remark` varchar(256) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师排班表';

-- booking_offpeak_rule 闲时规则表
CREATE TABLE IF NOT EXISTS `booking_offpeak_rule` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `name` varchar(64) NOT NULL COMMENT '规则名称',
    `week_days` varchar(32) DEFAULT NULL COMMENT '适用星期（1-7逗号分隔）',
    `start_time` time NOT NULL COMMENT '开始时间',
    `end_time` time NOT NULL COMMENT '结束时间',
    `discount_type` tinyint NOT NULL DEFAULT 1 COMMENT '优惠类型：1折扣 2固定减免',
    `discount_value` int NOT NULL COMMENT '优惠值（折扣为百分比，减免为分）',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0启用 1禁用',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '闲时规则表';

-- technician_commission 技师佣金记录表
CREATE TABLE IF NOT EXISTS `technician_commission` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `technician_id` bigint NOT NULL COMMENT '技师ID',
    `order_id` bigint NOT NULL COMMENT '预约订单ID',
    `user_id` bigint NOT NULL COMMENT '用户ID',
    `store_id` bigint DEFAULT NULL COMMENT '门店ID',
    `commission_type` tinyint NOT NULL COMMENT '佣金类型',
    `base_amount` int NOT NULL DEFAULT 0 COMMENT '订单金额（分）',
    `commission_rate` decimal(5, 4) NOT NULL DEFAULT 0 COMMENT '佣金比例',
    `commission_amount` int NOT NULL DEFAULT 0 COMMENT '佣金金额（分）',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态 0待结算 1已结算 2已取消',
    `settlement_id` bigint DEFAULT NULL COMMENT '结算单ID',
    `settlement_time` timestamp DEFAULT NULL COMMENT '结算时间',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师佣金记录表';

-- technician_commission_config 技师佣金配置表
CREATE TABLE IF NOT EXISTS `technician_commission_config` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` bigint NOT NULL COMMENT '门店ID',
    `commission_type` tinyint NOT NULL COMMENT '佣金类型',
    `rate` decimal(5, 4) NOT NULL DEFAULT 0 COMMENT '佣金比例',
    `fixed_amount` int NOT NULL DEFAULT 0 COMMENT '固定金额（分）',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师佣金配置表';

-- technician_commission_settlement 技师佣金结算单
CREATE TABLE IF NOT EXISTS `technician_commission_settlement` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `settlement_no` varchar(64) NOT NULL DEFAULT '',
    `store_id` bigint DEFAULT NULL,
    `technician_id` bigint NOT NULL,
    `status` tinyint NOT NULL DEFAULT 0,
    `commission_count` int NOT NULL DEFAULT 0,
    `total_commission_amount` int NOT NULL DEFAULT 0,
    `review_submit_time` timestamp DEFAULT NULL,
    `review_deadline_time` timestamp DEFAULT NULL,
    `review_warned` bit NOT NULL DEFAULT FALSE,
    `review_warn_time` timestamp DEFAULT NULL,
    `review_escalated` bit NOT NULL DEFAULT FALSE,
    `review_escalate_time` timestamp DEFAULT NULL,
    `reviewed_time` timestamp DEFAULT NULL,
    `reviewer_id` bigint DEFAULT NULL,
    `review_remark` varchar(255) NOT NULL DEFAULT '',
    `reject_reason` varchar(255) NOT NULL DEFAULT '',
    `paid_time` timestamp DEFAULT NULL,
    `payer_id` bigint DEFAULT NULL,
    `pay_voucher_no` varchar(64) NOT NULL DEFAULT '',
    `pay_remark` varchar(255) NOT NULL DEFAULT '',
    `remark` varchar(255) NOT NULL DEFAULT '',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师佣金结算单';

-- technician_commission_settlement_log 技师佣金结算单操作日志
CREATE TABLE IF NOT EXISTS `technician_commission_settlement_log` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `settlement_id` bigint NOT NULL,
    `action` varchar(32) NOT NULL DEFAULT '',
    `from_status` tinyint DEFAULT NULL,
    `to_status` tinyint DEFAULT NULL,
    `operator_id` bigint DEFAULT NULL,
    `operator_type` varchar(32) NOT NULL DEFAULT '',
    `operate_remark` varchar(255) NOT NULL DEFAULT '',
    `action_time` timestamp DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师佣金结算单操作日志';

-- technician_commission_settlement_notify_outbox 技师佣金结算通知出站表
CREATE TABLE IF NOT EXISTS `technician_commission_settlement_notify_outbox` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `settlement_id` bigint NOT NULL,
    `notify_type` varchar(32) NOT NULL DEFAULT '',
    `channel` varchar(32) NOT NULL DEFAULT '',
    `severity` varchar(8) NOT NULL DEFAULT '',
    `biz_key` varchar(128) NOT NULL DEFAULT '',
    `status` tinyint NOT NULL DEFAULT 0,
    `retry_count` int NOT NULL DEFAULT 0,
    `next_retry_time` timestamp DEFAULT NULL,
    `sent_time` timestamp DEFAULT NULL,
    `last_error_msg` varchar(255) NOT NULL DEFAULT '',
    `last_action_code` varchar(64) NOT NULL DEFAULT '',
    `last_action_biz_no` varchar(64) NOT NULL DEFAULT '',
    `last_action_time` timestamp DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '技师佣金结算通知出站表';
