#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'USAGE'
Usage:
  script/dev/run_wx_partner_real_pay_refund.sh

Env:
  BASE_URL=http://127.0.0.1:48080
  USERNAME=admin
  PASSWORD=admin123
  OPENID=<required>                           # 小程序 openid
  CHANNEL_CODE=wx_lite
  SPU_ID=1                                    # 1=0.01 元
  PARTNER_PAYER_MODE=auto|sp|sub              # default auto
  RUN_REFUND=1                                # 1=尝试退款；仅在支付成功后执行
  TENANT_ID=1
  PAY_APP_ID=1
  CHECK_OPENID_CHAIN=1                        # 1=执行openid链路一致性前置检查
  POLL_SECONDS=300                            # 支付/退款轮询窗口
  POLL_INTERVAL_SECONDS=3
  REQUEST_TIMEOUT_SECONDS=20
  ARTIFACT_BASE_DIR=.tmp/payment_real_flow
  RUN_ID=<auto-generated>

  DB_HOST=127.0.0.1
  DB_PORT=13306
  DB_NAME=hxy_dev
  DB_USER=hxy_pay
  DB_PASSWORD=123456

Exit:
  0: #26/#27 成功
  1: 任一步骤失败（保留完整证据到产物目录）
USAGE
  exit 0
fi

for cmd in curl jq mysql; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "[real-flow][FAIL] missing command: ${cmd}" >&2
    exit 1
  fi
done

BASE_URL="${BASE_URL:-http://127.0.0.1:48080}"
USERNAME="${USERNAME:-admin}"
PASSWORD="${PASSWORD:-admin123}"
OPENID="${OPENID:-}"
CHANNEL_CODE="${CHANNEL_CODE:-wx_lite}"
SPU_ID="${SPU_ID:-1}"
PARTNER_PAYER_MODE="${PARTNER_PAYER_MODE:-auto}"
RUN_REFUND="${RUN_REFUND:-1}"
TENANT_ID="${TENANT_ID:-1}"
PAY_APP_ID="${PAY_APP_ID:-1}"
CHECK_OPENID_CHAIN="${CHECK_OPENID_CHAIN:-1}"
POLL_SECONDS="${POLL_SECONDS:-300}"
POLL_INTERVAL_SECONDS="${POLL_INTERVAL_SECONDS:-3}"
REQUEST_TIMEOUT_SECONDS="${REQUEST_TIMEOUT_SECONDS:-20}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)_$RANDOM}"
ARTIFACT_BASE_DIR="${ARTIFACT_BASE_DIR:-${ROOT_DIR}/.tmp/payment_real_flow}"
ARTIFACT_DIR="${ARTIFACT_BASE_DIR}/${RUN_ID}"
LOG_DIR="${ARTIFACT_DIR}/logs"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-13306}"
DB_NAME="${DB_NAME:-hxy_dev}"
DB_USER="${DB_USER:-hxy_pay}"
DB_PASSWORD="${DB_PASSWORD:-123456}"

if [[ -z "${OPENID}" ]]; then
  echo "[real-flow][FAIL] OPENID is required" >&2
  exit 1
fi
if [[ "${PARTNER_PAYER_MODE}" != "auto" && "${PARTNER_PAYER_MODE}" != "sp" && "${PARTNER_PAYER_MODE}" != "sub" ]]; then
  echo "[real-flow][FAIL] PARTNER_PAYER_MODE only supports auto|sp|sub" >&2
  exit 1
fi

if [[ "${CHECK_OPENID_CHAIN}" == "1" ]]; then
  OPENID_CHAIN_CHECKER="${ROOT_DIR}/script/dev/check_wx_openid_chain_consistency.sh"
  if [[ ! -x "${OPENID_CHAIN_CHECKER}" ]]; then
    echo "[real-flow][FAIL] openid chain checker not found or not executable: ${OPENID_CHAIN_CHECKER}" >&2
    exit 1
  fi
  echo "[real-flow] preflight: checking wx openid chain consistency"
  DB_HOST="${DB_HOST}" \
  DB_PORT="${DB_PORT}" \
  DB_NAME="${DB_NAME}" \
  DB_USER="${DB_USER}" \
  DB_PASSWORD="${DB_PASSWORD}" \
  TENANT_ID="${TENANT_ID}" \
  PAY_APP_ID="${PAY_APP_ID}" \
  CHANNEL_CODE="${CHANNEL_CODE}" \
  "${OPENID_CHAIN_CHECKER}"
fi

mkdir -p "${ARTIFACT_DIR}" "${LOG_DIR}"
RUN_LOG="${LOG_DIR}/run.log"
exec > >(tee -a "${RUN_LOG}") 2>&1

MYSQL_CMD=(mysql "-h${DB_HOST}" "-P${DB_PORT}" "-u${DB_USER}" "-p${DB_PASSWORD}" "${DB_NAME}" -N -s)

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }

json_api() {
  local method="$1"
  local path="$2"
  local body="$3"
  local token="${4:-}"
  local output_file="$5"
  local auth_header=()
  local tenant_header=(-H "tenant-id: ${TENANT_ID}")
  if [[ -n "${token}" ]]; then
    auth_header=(-H "Authorization: Bearer ${token}")
  fi
  local resp_file="${output_file}.tmp"
  local http_code
  http_code="$(
    curl -sS -m "${REQUEST_TIMEOUT_SECONDS}" -X "${method}" \
      "${BASE_URL}${path}" \
      -H "Content-Type: application/json" \
      "${tenant_header[@]}" \
      "${auth_header[@]}" \
      -d "${body}" \
      -o "${resp_file}" \
      -w "%{http_code}" || true
  )"
  mv "${resp_file}" "${output_file}"
  echo "${http_code}"
}

api_put_no_body() {
  local path="$1"
  local token="$2"
  local output_file="$3"
  local resp_file="${output_file}.tmp"
  local http_code
  http_code="$(
    curl -sS -m "${REQUEST_TIMEOUT_SECONDS}" -X PUT \
      "${BASE_URL}${path}" \
      -H "tenant-id: ${TENANT_ID}" \
      -H "Authorization: Bearer ${token}" \
      -o "${resp_file}" \
      -w "%{http_code}" || true
  )"
  mv "${resp_file}" "${output_file}"
  echo "${http_code}"
}

query_single() {
  local sql="$1"
  "${MYSQL_CMD[@]}" -e "${sql}" 2>/dev/null | head -n 1 || true
}

dump_sql() {
  local sql="$1"
  local out="$2"
  "${MYSQL_CMD[@]}" -e "${sql}" > "${out}" 2>/dev/null || true
}

echo "[real-flow] start_at=$(ts)"
echo "[real-flow] run_id=${RUN_ID}"
echo "[real-flow] base_url=${BASE_URL}"
echo "[real-flow] channel=${CHANNEL_CODE} spu_id=${SPU_ID} partner_payer_mode=${PARTNER_PAYER_MODE} run_refund=${RUN_REFUND}"

LOGIN_BODY="$(jq -nc --arg username "${USERNAME}" --arg password "${PASSWORD}" '{username: $username, password: $password}')"
LOGIN_HTTP_CODE="$(json_api "POST" "/admin-api/system/auth/login" "${LOGIN_BODY}" "" "${ARTIFACT_DIR}/api_login.json")"
echo "[real-flow] login_http_code=${LOGIN_HTTP_CODE}"
if [[ "${LOGIN_HTTP_CODE}" != "200" ]]; then
  echo "[real-flow][FAIL] login http failed"
  exit 1
fi
TOKEN="$(jq -r '.data.accessToken // empty' "${ARTIFACT_DIR}/api_login.json")"
if [[ -z "${TOKEN}" ]]; then
  echo "[real-flow][FAIL] login token missing"
  exit 1
fi

CREATE_BODY="$(jq -nc --argjson spuId "${SPU_ID}" '{spuId: $spuId}')"
CREATE_HTTP_CODE="$(json_api "POST" "/admin-api/pay/demo-order/create" "${CREATE_BODY}" "${TOKEN}" "${ARTIFACT_DIR}/api_create_order.json")"
echo "[real-flow] create_http_code=${CREATE_HTTP_CODE}"
if [[ "${CREATE_HTTP_CODE}" != "200" ]]; then
  echo "[real-flow][FAIL] create demo order http failed"
  exit 1
fi
CREATE_BIZ_CODE="$(jq -r '.code // -1' "${ARTIFACT_DIR}/api_create_order.json")"
if [[ "${CREATE_BIZ_CODE}" != "0" ]]; then
  echo "[real-flow][FAIL] create demo order biz failed: code=${CREATE_BIZ_CODE} msg=$(jq -r '.msg // ""' "${ARTIFACT_DIR}/api_create_order.json")"
  exit 1
fi
DEMO_ORDER_ID="$(jq -r '.data // empty' "${ARTIFACT_DIR}/api_create_order.json")"
if [[ -z "${DEMO_ORDER_ID}" ]]; then
  echo "[real-flow][FAIL] demo order id missing"
  exit 1
fi
echo "[real-flow] demo_order_id=${DEMO_ORDER_ID}"

PAY_ORDER_ID="$(query_single "SELECT pay_order_id FROM pay_demo_order WHERE id=${DEMO_ORDER_ID};")"
if [[ -z "${PAY_ORDER_ID}" ]]; then
  echo "[real-flow][FAIL] pay_order_id missing for demo_order_id=${DEMO_ORDER_ID}"
  exit 1
fi
echo "[real-flow] pay_order_id=${PAY_ORDER_ID}"

CHANNEL_EXTRAS="$(jq -nc --arg openid "${OPENID}" '{openid: $openid}')"
if [[ "${PARTNER_PAYER_MODE}" == "sp" ]]; then
  CHANNEL_EXTRAS="$(jq -nc --arg openid "${OPENID}" '{openid: $openid, spOpenid: $openid, partnerPayerMode: "sp"}')"
elif [[ "${PARTNER_PAYER_MODE}" == "sub" ]]; then
  CHANNEL_EXTRAS="$(jq -nc --arg openid "${OPENID}" '{openid: $openid, subOpenid: $openid, partnerPayerMode: "sub"}')"
fi

SUBMIT_BODY="$(jq -nc \
  --argjson id "${PAY_ORDER_ID}" \
  --arg channelCode "${CHANNEL_CODE}" \
  --argjson channelExtras "${CHANNEL_EXTRAS}" \
  '{id: $id, channelCode: $channelCode, channelExtras: $channelExtras}')"
SUBMIT_HTTP_CODE="$(json_api "POST" "/admin-api/pay/order/submit" "${SUBMIT_BODY}" "${TOKEN}" "${ARTIFACT_DIR}/api_submit_order.json")"
echo "[real-flow] submit_http_code=${SUBMIT_HTTP_CODE}"

dump_sql "SELECT id, pay_order_id, pay_status, pay_time, pay_refund_id, refund_time FROM pay_demo_order WHERE id=${DEMO_ORDER_ID};" \
  "${ARTIFACT_DIR}/db_demo_order.tsv"
dump_sql "SELECT id, app_id, merchant_order_id, status, price, pay_price, refund_price, channel_id, channel_code, success_time FROM pay_order WHERE id=${PAY_ORDER_ID};" \
  "${ARTIFACT_DIR}/db_pay_order.tsv"
dump_sql "SELECT id, no, order_id, status, channel_error_code, channel_error_msg, channel_notify_data, update_time FROM pay_order_extension WHERE order_id=${PAY_ORDER_ID} ORDER BY id DESC LIMIT 1;" \
  "${ARTIFACT_DIR}/db_pay_order_extension.tsv"

if [[ "${SUBMIT_HTTP_CODE}" != "200" ]]; then
  echo "[real-flow][FAIL] submit order http failed"
  exit 1
fi
SUBMIT_BIZ_CODE="$(jq -r '.code // -1' "${ARTIFACT_DIR}/api_submit_order.json")"
if [[ "${SUBMIT_BIZ_CODE}" != "0" ]]; then
  echo "[real-flow][FAIL] submit order biz failed: code=${SUBMIT_BIZ_CODE} msg=$(jq -r '.msg // ""' "${ARTIFACT_DIR}/api_submit_order.json")"
  exit 1
fi
echo "[real-flow] submit order accepted"

PAY_STATUS=""
PAY_DEADLINE=$(( $(date +%s) + POLL_SECONDS ))
while [[ $(date +%s) -le ${PAY_DEADLINE} ]]; do
  PAY_STATUS="$(query_single "SELECT status FROM pay_order WHERE id=${PAY_ORDER_ID};")"
  if [[ "${PAY_STATUS}" == "10" || "${PAY_STATUS}" == "20" ]]; then
    break
  fi
  if [[ "${PAY_STATUS}" == "30" ]]; then
    break
  fi
  sleep "${POLL_INTERVAL_SECONDS}"
done
echo "[real-flow] pay_status=${PAY_STATUS:-unknown}"

if [[ "${PAY_STATUS}" != "10" && "${PAY_STATUS}" != "20" ]]; then
  echo "[real-flow][FAIL] pay order not in paid state, skip refund"
  dump_sql "SELECT id, no, order_id, status, channel_error_code, channel_error_msg, channel_notify_data, update_time FROM pay_order_extension WHERE order_id=${PAY_ORDER_ID} ORDER BY id DESC LIMIT 3;" \
    "${ARTIFACT_DIR}/db_pay_order_extension_after_poll.tsv"
  exit 1
fi

if [[ "${RUN_REFUND}" != "1" ]]; then
  echo "[real-flow] RUN_REFUND=0 skip refund stage"
  cat > "${ARTIFACT_DIR}/summary.txt" <<EOF
run_id=${RUN_ID}
result=PASS_PAY_ONLY
demo_order_id=${DEMO_ORDER_ID}
pay_order_id=${PAY_ORDER_ID}
pay_status=${PAY_STATUS}
artifact_dir=${ARTIFACT_DIR}
EOF
  exit 0
fi

REFUND_HTTP_CODE="$(api_put_no_body "/admin-api/pay/demo-order/refund?id=${DEMO_ORDER_ID}" "${TOKEN}" "${ARTIFACT_DIR}/api_refund_order.json")"
echo "[real-flow] refund_http_code=${REFUND_HTTP_CODE}"
if [[ "${REFUND_HTTP_CODE}" != "200" ]]; then
  echo "[real-flow][FAIL] refund request http failed"
  exit 1
fi
REFUND_BIZ_CODE="$(jq -r '.code // -1' "${ARTIFACT_DIR}/api_refund_order.json")"
if [[ "${REFUND_BIZ_CODE}" != "0" ]]; then
  echo "[real-flow][FAIL] refund request biz failed: code=${REFUND_BIZ_CODE} msg=$(jq -r '.msg // ""' "${ARTIFACT_DIR}/api_refund_order.json")"
  exit 1
fi

REFUND_ID=""
REFUND_STATUS=""
REFUND_DEADLINE=$(( $(date +%s) + POLL_SECONDS ))
while [[ $(date +%s) -le ${REFUND_DEADLINE} ]]; do
  REFUND_ID="$(query_single "SELECT pay_refund_id FROM pay_demo_order WHERE id=${DEMO_ORDER_ID};")"
  if [[ -n "${REFUND_ID}" ]]; then
    REFUND_STATUS="$(query_single "SELECT status FROM pay_refund WHERE id=${REFUND_ID};")"
    if [[ "${REFUND_STATUS}" == "10" || "${REFUND_STATUS}" == "20" ]]; then
      break
    fi
  fi
  sleep "${POLL_INTERVAL_SECONDS}"
done
echo "[real-flow] refund_id=${REFUND_ID:-unknown} refund_status=${REFUND_STATUS:-unknown}"

dump_sql "SELECT id, pay_order_id, pay_status, pay_time, pay_refund_id, refund_time FROM pay_demo_order WHERE id=${DEMO_ORDER_ID};" \
  "${ARTIFACT_DIR}/db_demo_order_after_refund.tsv"
if [[ -n "${REFUND_ID}" ]]; then
  dump_sql "SELECT id, no, order_id, status, pay_price, refund_price, channel_refund_no, channel_error_code, channel_error_msg, update_time FROM pay_refund WHERE id=${REFUND_ID};" \
    "${ARTIFACT_DIR}/db_pay_refund.tsv"
fi

if [[ "${REFUND_STATUS}" != "10" ]]; then
  echo "[real-flow][FAIL] refund not success"
  exit 1
fi

cat > "${ARTIFACT_DIR}/summary.txt" <<EOF
run_id=${RUN_ID}
result=PASS_PAY_AND_REFUND
demo_order_id=${DEMO_ORDER_ID}
pay_order_id=${PAY_ORDER_ID}
pay_status=${PAY_STATUS}
refund_id=${REFUND_ID}
refund_status=${REFUND_STATUS}
artifact_dir=${ARTIFACT_DIR}
EOF

echo "[real-flow] PASS #26/#27"
