apiVersion: v1
kind: ConfigMap
metadata:
  name: crmeb-app-config
  namespace: crmeb
data:
  TZ: "Asia/Shanghai"
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/crmeb_java?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  CRMEB_IMAGE_PATH: "/data/images/"
