apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - admin-hpa.yaml
  - front-deployment.yaml
  - front-service.yaml
  - front-hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: crmeb
