apiVersion: v1
kind: Secret
metadata:
  name: crmeb-app-secret
  namespace: crmeb
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "crmeb"
  SPRING_DATASOURCE_PASSWORD: "change_me"
  SPRING_REDIS_PASSWORD: ""
