#!/usr/bin/env bash
set -euo pipefail

# 服务商+子商户参数一键填充脚本（小程序主链路）

APPID="${APPID:-}"
SP_MCHID="${SP_MCHID:-}"
SP_KEY="${SP_KEY:-}"
SUB_MCHID="${SUB_MCHID:-}"
SUB_APPID="${SUB_APPID:-}"
API_URL="${API_URL:-}"
SP_CERT_PATH="${SP_CERT_PATH:-}"
ENABLE_PAY="${ENABLE_PAY:-0}"
APPLY=0
SNAPSHOT_BEFORE_APPLY=1

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-crmeb_java}"
DB_USER="${DB_USER:-root}"
DB_PASS="${DB_PASS:-}"
MYSQL_DEFAULTS_FILE="${MYSQL_DEFAULTS_FILE:-}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="${ROOT_DIR}/runtime/payment_onboarding/fill-$(date '+%Y%m%d%H%M%S')"
mkdir -p "${RUN_DIR}"
SQL_FILE="${RUN_DIR}/apply.sql"
SUMMARY_FILE="${RUN_DIR}/summary.txt"

usage() {
  cat <<'USAGE'
用法：
  ./shell/payment_service_provider_fill.sh [--apply] [--no-snapshot] --appid wx... --sp-mchid 19... --sp-key xxx --sub-mchid 19... [--sub-appid wx...] [--api-url https://xxx] [--sp-cert-path /path/apiclient_cert.p12]

参数：
  --appid            小程序 AppID（必填）
  --sp-mchid         微信支付服务商号（必填）
  --sp-key           微信支付 APIv2 Key（必填）
  --sub-mchid        默认子商户号（必填）
  --sub-appid        默认子商户 AppID（可选，默认等于 appid）
  --api-url          回调域名根地址（可选，建议 https）
  --sp-cert-path     服务商退款证书路径（可选）
  --enable-pay 0|1   是否开启支付开关（默认 0）
  --apply            真正写库（默认 dry-run）
  --no-snapshot      apply 前不做配置快照（默认会自动快照）

环境变量：
  DB_HOST DB_PORT DB_NAME DB_USER DB_PASS MYSQL_DEFAULTS_FILE
USAGE
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --appid) APPID="$2"; shift 2 ;;
    --sp-mchid) SP_MCHID="$2"; shift 2 ;;
    --sp-key) SP_KEY="$2"; shift 2 ;;
    --sub-mchid) SUB_MCHID="$2"; shift 2 ;;
    --sub-appid) SUB_APPID="$2"; shift 2 ;;
    --api-url) API_URL="$2"; shift 2 ;;
    --sp-cert-path) SP_CERT_PATH="$2"; shift 2 ;;
    --enable-pay) ENABLE_PAY="$2"; shift 2 ;;
    --apply) APPLY=1; shift ;;
    --no-snapshot) SNAPSHOT_BEFORE_APPLY=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "未知参数: $1"; usage; exit 1 ;;
  esac
done

if [[ -z "${APPID}" || -z "${SP_MCHID}" || -z "${SP_KEY}" || -z "${SUB_MCHID}" ]]; then
  echo "错误：缺少必填参数（appid/sp-mchid/sp-key/sub-mchid）"
  exit 1
fi
if [[ "${ENABLE_PAY}" != "0" && "${ENABLE_PAY}" != "1" ]]; then
  echo "错误：--enable-pay 仅支持 0/1"
  exit 1
fi
if [[ -z "${SUB_APPID}" ]]; then
  SUB_APPID="${APPID}"
fi
if [[ -n "${MYSQL_DEFAULTS_FILE}" && ! -f "${MYSQL_DEFAULTS_FILE}" ]]; then
  echo "错误：MYSQL_DEFAULTS_FILE 文件不存在 -> ${MYSQL_DEFAULTS_FILE}"
  exit 1
fi

APPID_ESC="$(sql_escape "${APPID}")"
SP_MCHID_ESC="$(sql_escape "${SP_MCHID}")"
SP_KEY_ESC="$(sql_escape "${SP_KEY}")"
SUB_MCHID_ESC="$(sql_escape "${SUB_MCHID}")"
SUB_APPID_ESC="$(sql_escape "${SUB_APPID}")"
API_URL_ESC="$(sql_escape "${API_URL}")"
SP_CERT_PATH_ESC="$(sql_escape "${SP_CERT_PATH}")"

cat > "${SQL_FILE}" <<SQL
-- generated by payment_service_provider_fill.sh
START TRANSACTION;

UPDATE eb_system_config SET value='${APPID_ESC}', update_time=NOW() WHERE name='pay_routine_sp_appid';
UPDATE eb_system_config SET value='${APPID_ESC}', update_time=NOW() WHERE name='pay_routine_appid';
UPDATE eb_system_config SET value='${SUB_APPID_ESC}', update_time=NOW() WHERE name='pay_routine_sub_appid';

UPDATE eb_system_config SET value='${SP_MCHID_ESC}', update_time=NOW() WHERE name='pay_routine_sp_mchid';
UPDATE eb_system_config SET value='${SP_KEY_ESC}', update_time=NOW() WHERE name='pay_routine_sp_key';
UPDATE eb_system_config SET value='${SUB_MCHID_ESC}', update_time=NOW() WHERE name='pay_routine_sub_mchid';

UPDATE eb_system_config SET value='${ENABLE_PAY}', update_time=NOW() WHERE name='pay_weixin_open';
SQL

if [[ -n "${API_URL}" ]]; then
cat >> "${SQL_FILE}" <<SQL
UPDATE eb_system_config SET value='${API_URL_ESC}', update_time=NOW() WHERE name='api_url';
SQL
fi

if [[ -n "${SP_CERT_PATH}" ]]; then
cat >> "${SQL_FILE}" <<SQL
UPDATE eb_system_config SET value='${SP_CERT_PATH_ESC}', update_time=NOW() WHERE name='pay_routine_sp_certificate_path';
SQL
fi

cat >> "${SQL_FILE}" <<'SQL'
COMMIT;
SQL

MYSQL_CMD=(mysql)
if [[ -n "${MYSQL_DEFAULTS_FILE}" ]]; then
  MYSQL_CMD+=(--defaults-extra-file="${MYSQL_DEFAULTS_FILE}")
  if [[ "${DB_USER}" == "root" && -z "${DB_PASS}" ]]; then
    DB_USER=""
  fi
fi
MYSQL_CMD+=(-h "${DB_HOST}" -P "${DB_PORT}")
if [[ -n "${DB_USER}" ]]; then
  MYSQL_CMD+=(-u "${DB_USER}")
fi
MYSQL_CMD+=("${DB_NAME}" --default-character-set=utf8mb4)
if [[ -n "${DB_PASS}" && -z "${MYSQL_DEFAULTS_FILE}" ]]; then
  MYSQL_CMD+=(--password="${DB_PASS}")
fi

{
  echo "run_dir=${RUN_DIR}"
  echo "sql_file=${SQL_FILE}"
  echo "apply=${APPLY}"
  echo "snapshot_before_apply=${SNAPSHOT_BEFORE_APPLY}"
  echo "appid=${APPID}"
  echo "sp_mchid=${SP_MCHID}"
  echo "sub_mchid=${SUB_MCHID}"
  echo "sub_appid=${SUB_APPID}"
  echo "api_url=${API_URL:-<unchanged>}"
  echo "sp_cert_path=${SP_CERT_PATH:-<unchanged>}"
  echo "enable_pay=${ENABLE_PAY}"
} > "${SUMMARY_FILE}"

if [[ ${APPLY} -eq 0 ]]; then
  echo "dry-run 完成，未写库。"
  echo "产物目录: ${RUN_DIR}"
  echo "SQL 文件: ${SQL_FILE}"
  exit 0
fi

if [[ ${SNAPSHOT_BEFORE_APPLY} -eq 1 ]]; then
  SNAPSHOT_SCRIPT="${ROOT_DIR}/shell/payment_config_snapshot.sh"
  if [[ -x "${SNAPSHOT_SCRIPT}" ]]; then
    snapshot_output="$("${SNAPSHOT_SCRIPT}" --tag "service-provider-fill" 2>&1)"
    echo "${snapshot_output}"
    snapshot_dir="$(printf '%s\n' "${snapshot_output}" | sed -n 's/^\[config-snapshot\] run_dir=//p' | tail -n 1)"
    if [[ -n "${snapshot_dir}" ]]; then
      echo "snapshot_dir=${snapshot_dir}" >> "${SUMMARY_FILE}"
    fi
  else
    echo "错误：未找到快照脚本 -> ${SNAPSHOT_SCRIPT}"
    exit 1
  fi
fi

"${MYSQL_CMD[@]}" < "${SQL_FILE}"
echo "写库完成。产物目录: ${RUN_DIR}"
