#!/usr/bin/env bash
set -euo pipefail

# 支付配置快照脚本
# 输出：
# 1) snapshot.tsv
# 2) restore.sql（可用于回滚）
# 3) summary.txt

TAG="${TAG:-}"
OUT_DIR="${OUT_DIR:-}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-crmeb_java}"
DB_USER="${DB_USER:-root}"
DB_PASS="${DB_PASS:-}"
MYSQL_DEFAULTS_FILE="${MYSQL_DEFAULTS_FILE:-}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

KEYS=(
  "pay_weixin_open"
  "api_url"
  "pay_routine_appid"
  "pay_routine_mchid"
  "pay_routine_key"
  "pay_routine_sp_appid"
  "pay_routine_sp_mchid"
  "pay_routine_sp_key"
  "pay_routine_sub_mchid"
  "pay_routine_sub_appid"
  "pay_routine_sp_certificate_path"
)

usage() {
  cat <<'USAGE'
用法：
  ./shell/payment_config_snapshot.sh [--tag TAG] [--out-dir PATH]

参数：
  --tag TAG         快照标签（可选）
  --out-dir PATH    输出根目录（默认 runtime/payment_config_snapshot）

环境变量：
  DB_HOST DB_PORT DB_NAME DB_USER DB_PASS MYSQL_DEFAULTS_FILE

退出码：
  0  快照成功
  1  执行失败
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)
      TAG="$2"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "未知参数: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -n "${MYSQL_DEFAULTS_FILE}" && ! -f "${MYSQL_DEFAULTS_FILE}" ]]; then
  echo "参数错误: MYSQL_DEFAULTS_FILE 文件不存在 -> ${MYSQL_DEFAULTS_FILE}"
  exit 1
fi

if [[ -z "${OUT_DIR}" ]]; then
  OUT_DIR="${ROOT_DIR}/runtime/payment_config_snapshot"
fi
mkdir -p "${OUT_DIR}"

tag_suffix=""
if [[ -n "${TAG}" ]]; then
  safe_tag="$(printf '%s' "${TAG}" | sed 's/[^A-Za-z0-9._-]/_/g')"
  tag_suffix="-${safe_tag}"
fi
RUN_ID="$(date '+%Y%m%d%H%M%S')-$$"
RUN_DIR="${OUT_DIR}/snapshot-${RUN_ID}${tag_suffix}"
mkdir -p "${RUN_DIR}"

SNAPSHOT_TSV="${RUN_DIR}/snapshot.tsv"
RESTORE_SQL="${RUN_DIR}/restore.sql"
SUMMARY_FILE="${RUN_DIR}/summary.txt"

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

MYSQL_CMD=(mysql)
if [[ -n "${MYSQL_DEFAULTS_FILE}" ]]; then
  MYSQL_CMD+=(--defaults-extra-file="${MYSQL_DEFAULTS_FILE}")
  if [[ "${DB_USER}" == "root" && -z "${DB_PASS}" ]]; then
    DB_USER=""
  fi
fi
MYSQL_CMD+=(-h "${DB_HOST}" -P "${DB_PORT}")
if [[ -n "${DB_USER}" ]]; then
  MYSQL_CMD+=(-u "${DB_USER}")
fi
MYSQL_CMD+=("${DB_NAME}" --default-character-set=utf8mb4 --batch --raw --skip-column-names)
if [[ -n "${DB_PASS}" && -z "${MYSQL_DEFAULTS_FILE}" ]]; then
  MYSQL_CMD+=(--password="${DB_PASS}")
fi

key_sql=""
for k in "${KEYS[@]}"; do
  k_esc="$(sql_escape "${k}")"
  if [[ -n "${key_sql}" ]]; then
    key_sql="${key_sql},"
  fi
  key_sql="${key_sql}'${k_esc}'"
done

declare -A V_MAP=()
declare -A T_MAP=()
declare -A F_MAP=()
declare -A S_MAP=()

rows="$("${MYSQL_CMD[@]}" -e "
SELECT CONCAT(
  name, 0x1F,
  IFNULL(REPLACE(value, 0x1F, ''), ''), 0x1F,
  IFNULL(REPLACE(title, 0x1F, ''), ''), 0x1F,
  IFNULL(form_id,0), 0x1F,
  IFNULL(status,1)
)
FROM eb_system_config
WHERE name IN (${key_sql});
")"

while IFS=$'\x1f' read -r name value title form_id status; do
  [[ -z "${name}" ]] && continue
  V_MAP["${name}"]="${value}"
  T_MAP["${name}"]="${title}"
  F_MAP["${name}"]="${form_id}"
  S_MAP["${name}"]="${status}"
done <<< "${rows}"

printf "name\texists\tvalue\ttitle\tform_id\tstatus\n" > "${SNAPSHOT_TSV}"

captured_count=0
missing_count=0
for k in "${KEYS[@]}"; do
  if [[ -v V_MAP["${k}"] ]]; then
    captured_count=$((captured_count + 1))
    printf "%s\t1\t%s\t%s\t%s\t%s\n" \
      "${k}" "${V_MAP[${k}]}" "${T_MAP[${k}]}" "${F_MAP[${k}]}" "${S_MAP[${k}]}" >> "${SNAPSHOT_TSV}"
  else
    missing_count=$((missing_count + 1))
    printf "%s\t0\t\t\t\t\n" "${k}" >> "${SNAPSHOT_TSV}"
  fi
done

{
  echo "-- payment config restore generated by payment_config_snapshot.sh"
  echo "-- run_id: ${RUN_ID}"
  echo "-- tag: ${TAG}"
  echo "-- source_snapshot: ${SNAPSHOT_TSV}"
  echo "START TRANSACTION;"
} > "${RESTORE_SQL}"

for k in "${KEYS[@]}"; do
  if [[ ! -v V_MAP["${k}"] ]]; then
    continue
  fi
  k_esc="$(sql_escape "${k}")"
  v_esc="$(sql_escape "${V_MAP[${k}]}")"
  t_esc="$(sql_escape "${T_MAP[${k}]}")"
  f_raw="${F_MAP[${k}]}"
  s_raw="${S_MAP[${k}]}"
  if [[ -z "${f_raw}" ]]; then f_raw="0"; fi
  if [[ -z "${s_raw}" ]]; then s_raw="1"; fi

  cat >> "${RESTORE_SQL}" <<SQL
UPDATE eb_system_config
SET value='${v_esc}', title='${t_esc}', form_id=${f_raw}, status=${s_raw}, update_time=NOW()
WHERE name='${k_esc}';

INSERT INTO eb_system_config(name, title, form_id, value, status, create_time, update_time)
SELECT '${k_esc}', '${t_esc}', ${f_raw}, '${v_esc}', ${s_raw}, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM eb_system_config WHERE name='${k_esc}');
SQL
done

echo "COMMIT;" >> "${RESTORE_SQL}"

cat > "${SUMMARY_FILE}" <<TXT
run_id=${RUN_ID}
run_time=$(date '+%Y-%m-%d %H:%M:%S')
tag=${TAG}
run_dir=${RUN_DIR}
snapshot_file=${SNAPSHOT_TSV}
restore_sql=${RESTORE_SQL}
target_key_count=${#KEYS[@]}
captured_count=${captured_count}
missing_count=${missing_count}
TXT

echo "[config-snapshot] run_dir=${RUN_DIR}"
echo "[config-snapshot] snapshot=${SNAPSHOT_TSV}"
echo "[config-snapshot] restore_sql=${RESTORE_SQL}"

exit 0
