package com.hxy.module.booking.dal.mysql;

import com.hxy.module.booking.controller.admin.vo.BookingRefundReplayRunDetailPageReqVO;
import com.hxy.module.booking.controller.admin.vo.BookingRefundReplayRunDetailRespVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface BookingRefundReplayRunDetailQueryMapper {

    @Select({
            "<script>",
            "SELECT COUNT(1)",
            "FROM hxy_booking_refund_replay_run_detail d",
            "LEFT JOIN (",
            "  SELECT l.run_id, l.notify_log_id, l.ticket_id, l.status, l.sync_time, l.error_code, l.error_msg",
            "  FROM hxy_booking_refund_replay_ticket_sync_log l",
            "  INNER JOIN (",
            "    SELECT run_id, notify_log_id, MAX(id) AS max_id",
            "    FROM hxy_booking_refund_replay_ticket_sync_log",
            "    WHERE deleted = 0",
            "    GROUP BY run_id, notify_log_id",
            "  ) latest ON l.id = latest.max_id",
            "  WHERE l.deleted = 0",
            ") s ON s.run_id = d.run_id AND s.notify_log_id = d.notify_log_id",
            "WHERE d.deleted = 0",
            "  <if test='req.runId != null and req.runId != \"\"'>",
            "    AND d.run_id = #{req.runId}",
            "  </if>",
            "  <if test='req.resultStatus != null and req.resultStatus != \"\"'>",
            "    AND d.result_status = #{req.resultStatus}",
            "  </if>",
            "  <if test='req.resultCode != null and req.resultCode != \"\"'>",
            "    AND d.result_code = #{req.resultCode}",
            "  </if>",
            "  <if test='req.warningTag != null and req.warningTag != \"\"'>",
            "    AND d.warning_tag = #{req.warningTag}",
            "  </if>",
            "  <if test='req.ticketSyncStatus != null and req.ticketSyncStatus != \"\"'>",
            "    AND s.status = #{req.ticketSyncStatus}",
            "  </if>",
            "  <if test='req.notifyLogId != null'>",
            "    AND d.notify_log_id = #{req.notifyLogId}",
            "  </if>",
            "  <if test='req.orderId != null'>",
            "    AND d.order_id = #{req.orderId}",
            "  </if>",
            "  <if test='req.payRefundId != null'>",
            "    AND d.pay_refund_id = #{req.payRefundId}",
            "  </if>",
            "</script>"
    })
    Long countDetailPage(@Param("req") BookingRefundReplayRunDetailPageReqVO reqVO);

    @Select({
            "<script>",
            "SELECT",
            "  d.id AS id,",
            "  d.run_id AS runId,",
            "  d.notify_log_id AS notifyLogId,",
            "  d.order_id AS orderId,",
            "  d.pay_refund_id AS payRefundId,",
            "  d.result_status AS resultStatus,",
            "  d.result_code AS resultCode,",
            "  d.result_msg AS resultMsg,",
            "  d.warning_tag AS warningTag,",
            "  s.status AS ticketSyncStatus,",
            "  s.ticket_id AS ticketId,",
            "  s.sync_time AS ticketSyncTime,",
            "  s.error_code AS ticketSyncErrorCode,",
            "  s.error_msg AS ticketSyncErrorMsg,",
            "  d.create_time AS createTime,",
            "  d.update_time AS updateTime",
            "FROM hxy_booking_refund_replay_run_detail d",
            "LEFT JOIN (",
            "  SELECT l.run_id, l.notify_log_id, l.ticket_id, l.status, l.sync_time, l.error_code, l.error_msg",
            "  FROM hxy_booking_refund_replay_ticket_sync_log l",
            "  INNER JOIN (",
            "    SELECT run_id, notify_log_id, MAX(id) AS max_id",
            "    FROM hxy_booking_refund_replay_ticket_sync_log",
            "    WHERE deleted = 0",
            "    GROUP BY run_id, notify_log_id",
            "  ) latest ON l.id = latest.max_id",
            "  WHERE l.deleted = 0",
            ") s ON s.run_id = d.run_id AND s.notify_log_id = d.notify_log_id",
            "WHERE d.deleted = 0",
            "  <if test='req.runId != null and req.runId != \"\"'>",
            "    AND d.run_id = #{req.runId}",
            "  </if>",
            "  <if test='req.resultStatus != null and req.resultStatus != \"\"'>",
            "    AND d.result_status = #{req.resultStatus}",
            "  </if>",
            "  <if test='req.resultCode != null and req.resultCode != \"\"'>",
            "    AND d.result_code = #{req.resultCode}",
            "  </if>",
            "  <if test='req.warningTag != null and req.warningTag != \"\"'>",
            "    AND d.warning_tag = #{req.warningTag}",
            "  </if>",
            "  <if test='req.ticketSyncStatus != null and req.ticketSyncStatus != \"\"'>",
            "    AND s.status = #{req.ticketSyncStatus}",
            "  </if>",
            "  <if test='req.notifyLogId != null'>",
            "    AND d.notify_log_id = #{req.notifyLogId}",
            "  </if>",
            "  <if test='req.orderId != null'>",
            "    AND d.order_id = #{req.orderId}",
            "  </if>",
            "  <if test='req.payRefundId != null'>",
            "    AND d.pay_refund_id = #{req.payRefundId}",
            "  </if>",
            "ORDER BY d.id DESC",
            "LIMIT #{offset}, #{pageSize}",
            "</script>"
    })
    List<BookingRefundReplayRunDetailRespVO> selectDetailPage(@Param("req") BookingRefundReplayRunDetailPageReqVO reqVO,
                                                               @Param("offset") Integer offset,
                                                               @Param("pageSize") Integer pageSize);

    @Select({
            "<script>",
            "SELECT",
            "  d.id AS id,",
            "  d.run_id AS runId,",
            "  d.notify_log_id AS notifyLogId,",
            "  d.order_id AS orderId,",
            "  d.pay_refund_id AS payRefundId,",
            "  d.result_status AS resultStatus,",
            "  d.result_code AS resultCode,",
            "  d.result_msg AS resultMsg,",
            "  d.warning_tag AS warningTag,",
            "  s.status AS ticketSyncStatus,",
            "  s.ticket_id AS ticketId,",
            "  s.sync_time AS ticketSyncTime,",
            "  s.error_code AS ticketSyncErrorCode,",
            "  s.error_msg AS ticketSyncErrorMsg,",
            "  d.create_time AS createTime,",
            "  d.update_time AS updateTime",
            "FROM hxy_booking_refund_replay_run_detail d",
            "LEFT JOIN (",
            "  SELECT l.run_id, l.notify_log_id, l.ticket_id, l.status, l.sync_time, l.error_code, l.error_msg",
            "  FROM hxy_booking_refund_replay_ticket_sync_log l",
            "  INNER JOIN (",
            "    SELECT run_id, notify_log_id, MAX(id) AS max_id",
            "    FROM hxy_booking_refund_replay_ticket_sync_log",
            "    WHERE deleted = 0",
            "    GROUP BY run_id, notify_log_id",
            "  ) latest ON l.id = latest.max_id",
            "  WHERE l.deleted = 0",
            ") s ON s.run_id = d.run_id AND s.notify_log_id = d.notify_log_id",
            "WHERE d.deleted = 0",
            "  AND d.id = #{id}",
            "LIMIT 1",
            "</script>"
    })
    BookingRefundReplayRunDetailRespVO selectDetailById(@Param("id") Long id);
}
