#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_FILE="${1:-$ROOT_DIR/sql/mysql/ruoyi-modules-member-pay-mall.sql}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

SOURCES=(
  "yudao-module-member/src/test/resources/sql/create_tables.sql"
  "yudao-module-pay/src/test/resources/sql/create_tables.sql"
  "yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql"
  "yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql"
  "yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql"
)

normalize_sql() {
  local source_file="$1"
  local source_tag="$2"
  local input_file="$source_file"

  if [[ "$source_tag" == "product" ]]; then
    input_file="$TMP_DIR/product-core.sql"
    # product 模块测试 SQL 末尾有一段不完整的 DROP TABLE 片段，生成初始化脚本时先裁掉
    awk '/DROP TABLE IF EXISTS `product_comment` \(/ {exit} {print}' "$source_file" > "$input_file"
  fi

  perl -pe '
    s/"([A-Za-z0-9_]+)"/`$1`/g;
    s/\bnumber\b/bigint/g;
    s/\blong\b/bigint/g;
    s/\bvarchar\b(?!\s*\()/varchar(255)/g;
    s/\bboolean\b/tinyint(1)/g;
    s/GENERATED BY DEFAULT AS IDENTITY/AUTO_INCREMENT/g;
    s/\bbit\b(?!\s*\()/bit(1)/g;
  ' "$input_file"
}

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "-- Auto-generated by script/sql/build_mysql_module_schema.sh"
  echo "-- Generated at: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "-- Scope: member + pay + mall(product/promotion/trade)"
  echo "SET NAMES utf8mb4;"
  echo "SET FOREIGN_KEY_CHECKS = 0;"
  echo

  for source in "${SOURCES[@]}"; do
    abs_source="$ROOT_DIR/$source"
    if [[ ! -f "$abs_source" ]]; then
      echo "-- Skip missing source: $source"
      echo
      continue
    fi

    case "$source" in
      *yudao-module-product*) tag="product" ;;
      *) tag="default" ;;
    esac

    echo "-- ------------------------------------------------------------------"
    echo "-- Source: $source"
    echo "-- ------------------------------------------------------------------"
    normalize_sql "$abs_source" "$tag"
    echo
  done

  echo "SET FOREIGN_KEY_CHECKS = 1;"
} > "$OUT_FILE"

echo "Generated: $OUT_FILE"
