-- 技师排班系统数据库表
-- 基于 RuoYi-Vue-Pro 框架

-- 1. 技师表
CREATE TABLE IF NOT EXISTS `booking_technician` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '技师编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `user_id` bigint DEFAULT NULL COMMENT '关联用户编号',
    `name` varchar(64) NOT NULL COMMENT '技师姓名',
    `avatar` varchar(512) DEFAULT NULL COMMENT '头像',
    `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
    `introduction` varchar(500) DEFAULT NULL COMMENT '简介',
    `tags` varchar(255) DEFAULT NULL COMMENT '标签（逗号分隔）',
    `rating` decimal(2,1) DEFAULT '5.0' COMMENT '评分',
    `service_count` int DEFAULT '0' COMMENT '服务次数',
    `sort` int DEFAULT '0' COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0正常 1停用）',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_store_id` (`store_id`),
    KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='技师表';

-- 2. 技师排班表（日维度）
CREATE TABLE IF NOT EXISTS `booking_technician_schedule` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '排班编号',
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `schedule_date` date NOT NULL COMMENT '排班日期',
    `week_day` tinyint NOT NULL COMMENT '星期几（0=周日 1=周一...6=周六）',
    `is_rest_day` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否休息日',
    `work_start_time` time DEFAULT '09:00:00' COMMENT '上班时间',
    `work_end_time` time DEFAULT '21:00:00' COMMENT '下班时间',
    `predicted_booking_rate` int DEFAULT NULL COMMENT '预测预约率',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_technician_date` (`technician_id`, `schedule_date`),
    KEY `idx_store_date` (`store_id`, `schedule_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='技师排班表';

-- 3. 时间槽表（小时维度）
CREATE TABLE IF NOT EXISTS `booking_time_slot` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '时间槽编号',
    `schedule_id` bigint NOT NULL COMMENT '排班编号',
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `slot_date` date NOT NULL COMMENT '日期',
    `start_time` time NOT NULL COMMENT '开始时间',
    `end_time` time NOT NULL COMMENT '结束时间',
    `duration` int NOT NULL DEFAULT '60' COMMENT '时长（分钟）',
    `is_offpeak` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否闲时',
    `offpeak_price` int DEFAULT NULL COMMENT '闲时价格（分）',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0可用 1锁定 2已预约 3已完成 4已取消）',
    `lock_expire_time` datetime DEFAULT NULL COMMENT '锁定过期时间',
    `lock_user_id` bigint DEFAULT NULL COMMENT '锁定用户编号',
    `booking_order_id` bigint DEFAULT NULL COMMENT '预约订单编号',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_schedule_id` (`schedule_id`),
    KEY `idx_technician_date` (`technician_id`, `slot_date`),
    KEY `idx_store_date_status` (`store_id`, `slot_date`, `status`),
    KEY `idx_lock_expire` (`status`, `lock_expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='时间槽表';

-- 4. 预约订单表
CREATE TABLE IF NOT EXISTS `booking_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '预约订单编号',
    `order_no` varchar(64) NOT NULL COMMENT '预约订单号',
    `user_id` bigint NOT NULL COMMENT '用户编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `technician_id` bigint NOT NULL COMMENT '技师编号',
    `time_slot_id` bigint NOT NULL COMMENT '时间槽编号',
    `spu_id` bigint DEFAULT NULL COMMENT '服务商品SPU编号',
    `sku_id` bigint DEFAULT NULL COMMENT '服务商品SKU编号',
    `service_name` varchar(128) DEFAULT NULL COMMENT '服务名称',
    `service_pic` varchar(512) DEFAULT NULL COMMENT '服务图片',
    `booking_date` date NOT NULL COMMENT '预约日期',
    `booking_start_time` time NOT NULL COMMENT '预约开始时间',
    `booking_end_time` time NOT NULL COMMENT '预约结束时间',
    `duration` int NOT NULL COMMENT '服务时长（分钟）',
    `original_price` int NOT NULL DEFAULT '0' COMMENT '原价（分）',
    `discount_price` int NOT NULL DEFAULT '0' COMMENT '优惠金额（分）',
    `pay_price` int NOT NULL DEFAULT '0' COMMENT '实付金额（分）',
    `is_offpeak` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否闲时优惠',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '订单状态（0待支付 1已支付 2服务中 3已完成 4已取消 5已退款）',
    `pay_order_id` bigint DEFAULT NULL COMMENT '支付订单编号',
    `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
    `service_start_time` datetime DEFAULT NULL COMMENT '服务开始时间',
    `service_end_time` datetime DEFAULT NULL COMMENT '服务结束时间',
    `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
    `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
    `user_remark` varchar(255) DEFAULT NULL COMMENT '用户备注',
    `merchant_remark` varchar(255) DEFAULT NULL COMMENT '商家备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_technician_date` (`technician_id`, `booking_date`),
    KEY `idx_store_date` (`store_id`, `booking_date`),
    KEY `idx_status` (`status`),
    KEY `idx_pay_order_id` (`pay_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='预约订单表';

-- 5. 闲时规则表
CREATE TABLE IF NOT EXISTS `booking_offpeak_rule` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '规则编号',
    `store_id` bigint NOT NULL COMMENT '门店编号',
    `name` varchar(64) NOT NULL COMMENT '规则名称',
    `week_days` varchar(32) DEFAULT NULL COMMENT '适用星期（逗号分隔，如：1,2,3,4,5）',
    `start_time` time NOT NULL COMMENT '开始时间',
    `end_time` time NOT NULL COMMENT '结束时间',
    `discount_rate` int DEFAULT NULL COMMENT '折扣比例（如：80表示8折）',
    `fixed_price` int DEFAULT NULL COMMENT '固定优惠价（分）',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0正常 1停用）',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_store_id` (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='闲时规则表';
