apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hxy-service-pdb
  namespace: hxy-prod-core
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hxy-service
