-- 门店 SKU 库存调整单（补货/调拨/盘点/损耗）最小闭环
CREATE TABLE IF NOT EXISTS `hxy_store_sku_stock_adjust_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` varchar(64) NOT NULL COMMENT '调整单号',
    `store_id` bigint NOT NULL COMMENT '门店ID',
    `store_name` varchar(64) NOT NULL DEFAULT '' COMMENT '门店名称',
    `biz_type` varchar(32) NOT NULL COMMENT '业务类型',
    `reason` varchar(255) NOT NULL DEFAULT '' COMMENT '原因',
    `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
    `status` tinyint NOT NULL COMMENT '状态：0草稿 10待审 20已通过 30已驳回 40已取消',
    `detail_json` text NOT NULL COMMENT '调整明细JSON',
    `apply_operator` varchar(64) NOT NULL DEFAULT '' COMMENT '申请人',
    `apply_source` varchar(32) NOT NULL DEFAULT 'ADMIN_UI' COMMENT '申请来源',
    `approve_operator` varchar(64) NOT NULL DEFAULT '' COMMENT '审批人',
    `approve_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '审批备注',
    `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
    `last_action_code` varchar(32) NOT NULL DEFAULT '' COMMENT '最后动作编码',
    `last_action_operator` varchar(64) NOT NULL DEFAULT '' COMMENT '最后动作操作人',
    `last_action_time` datetime DEFAULT NULL COMMENT '最后动作时间',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`, `deleted`),
    KEY `idx_store_status_time` (`store_id`, `status`, `create_time`),
    KEY `idx_biz_status_time` (`biz_type`, `status`, `create_time`),
    KEY `idx_last_action_time` (`last_action_code`, `last_action_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店SKU库存调整单';
