-- Auto-generated by script/sql/build_mysql_module_schema.sh
-- Generated at: 2026-02-19 10:10:10
-- Scope: member + pay + mall(product/promotion/trade)
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------------
-- Source: yudao-module-member/src/test/resources/sql/create_tables.sql
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `member_user`
(
    `id`          bigint       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `nickname`    varchar(30)  NOT NULL DEFAULT '' COMMENT '用户昵称',
    `name`        varchar(30)  NULL COMMENT '真实名字',
    sex           tinyint      null comment '性别',
    birthday      datetime     null comment '出生日期',
    area_id       int          null comment '所在地',
    mark          varchar(255) null comment '用户备注',
    point         int                   default 0 null comment '积分',
    `avatar`      varchar(255) NOT NULL DEFAULT '' COMMENT '头像',
    `status`      tinyint      NOT NULL COMMENT '状态',
    `mobile`      varchar(11)  NOT NULL COMMENT '手机号',
    `password`    varchar(100) NOT NULL DEFAULT '' COMMENT '密码',
    `register_ip` varchar(32)  NOT NULL COMMENT '注册 IP',
    `login_ip`    varchar(50)  NULL     DEFAULT '' COMMENT '最后登录IP',
    `login_date`  datetime     NULL     DEFAULT NULL COMMENT '最后登录时间',
    `tag_ids`     varchar(255) NULL     DEFAULT NULL COMMENT '用户标签编号列表,以逗号分隔',
    `level_id`    bigint       NULL     DEFAULT NULL COMMENT '等级编号',
    `experience`  bigint       NULL     DEFAULT NULL COMMENT '经验',
    `group_id`    bigint       NULL     DEFAULT NULL COMMENT '用户分组编号',
    `creator`     varchar(64)  NULL     DEFAULT '' COMMENT '创建者',
    `create_time` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`     varchar(64)  NULL     DEFAULT '' COMMENT '更新者',
    `update_time` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`     bit(1)       NOT NULL DEFAULT '0' COMMENT '是否删除',
    `tenant_id`   bigint       not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '会员表';

CREATE TABLE IF NOT EXISTS `member_address` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `user_id` bigint(20) NOT NULL,
    `name` varchar(10) NOT NULL,
    `mobile` varchar(20) NOT NULL,
    `area_id` bigint(20) NOT NULL,
    `detail_address` varchar(250) NOT NULL,
    `default_status` bit(1) NOT NULL,
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `creator` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `updater` varchar(64) DEFAULT '',
    PRIMARY KEY (`id`)
) COMMENT '用户收件地址';

CREATE TABLE IF NOT EXISTS `member_tag`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT,
    `name`        varchar(255)  NOT NULL,
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`   bigint   NOT NULL default '0',
    PRIMARY KEY (`id`)
) COMMENT '会员标签';

CREATE TABLE IF NOT EXISTS `member_level`
(
    `id`             bigint   NOT NULL AUTO_INCREMENT,
    `name`           varchar(255)  NOT NULL,
    `experience`     int      NOT NULL,
    `level`          int      NOT NULL,
    `discount_percent`       int      NOT NULL,
    `icon`           varchar(255)  NOT NULL,
    `background_url` varchar(255)  NOT NULL,
    `creator`        varchar(255)           DEFAULT '',
    `create_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`        varchar(255)           DEFAULT '',
    `update_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`        bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`      bigint   not null default '0',
    `status` tinyint NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
) COMMENT '会员等级';

CREATE TABLE IF NOT EXISTS `member_group`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT,
    `name`        varchar(255)  NOT NULL,
    `remark`      varchar(255)  NOT NULL,
    `status` tinyint NOT NULL DEFAULT '0',
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`      bigint   not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '用户分组';
CREATE TABLE IF NOT EXISTS `member_brokerage_record`
(
    `id`            int      NOT NULL AUTO_INCREMENT,
    `user_id`       bigint   NOT NULL,
    `biz_id`        varchar(255)  NOT NULL,
    `biz_type`      varchar(255)  NOT NULL,
    `title`         varchar(255)  NOT NULL,
    `price`         int      NOT NULL,
    `total_price`   int      NOT NULL,
    `description`   varchar(255)  NOT NULL,
    `status`        varchar(255)  NOT NULL,
    `frozen_days`   int      NOT NULL,
    `unfreeze_time` varchar(255),
    `creator`       varchar(255)           DEFAULT '',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`       varchar(255)           DEFAULT '',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`       bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`      bigint   not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '佣金记录';

-- ------------------------------------------------------------------
-- Source: yudao-module-pay/src/test/resources/sql/create_tables.sql
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_app` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `app_key`              varchar(64)   NOT NULL,
    `name`              varchar(64)   NOT NULL,
    `status`            tinyint       NOT NULL,
    `remark`            varchar(255)           DEFAULT NULL,
    `order_notify_url`    varchar(1024) NOT NULL,
    `refund_notify_url` varchar(1024) NOT NULL,
    `creator`           varchar(64)            DEFAULT '',
    `create_time`       datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`           varchar(64)            DEFAULT '',
    `update_time`       datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`           bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '支付应用';

CREATE TABLE IF NOT EXISTS `pay_channel` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `code`        varchar(32)    NOT NULL,
    `status`      tinyint(4)     NOT NULL,
    `remark`      varchar(255)            DEFAULT NULL,
    `fee_rate`    double         NOT NULL DEFAULT 0,
    `app_id`      bigint(20)     NOT NULL,
    `config`      varchar(10240) NOT NULL,
    `creator`     varchar(64)    NULL     DEFAULT '',
    `create_time` datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(64)    NULL     DEFAULT '',
    `update_time` datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)         NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    PRIMARY KEY (`id`)
) COMMENT = '支付渠道';

CREATE TABLE IF NOT EXISTS `pay_order` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `app_id`               bigint(20)    NOT NULL,
    `channel_id`           bigint(20)             DEFAULT NULL,
    `channel_code`         varchar(32)            DEFAULT NULL,
    `merchant_order_id`    varchar(64)   NOT NULL,
    `subject`              varchar(32)   NOT NULL,
    `body`                 varchar(128)  NOT NULL,
    `notify_url`           varchar(1024) NOT NULL,
    `price`                bigint(20)    NOT NULL,
    `channel_fee_rate`     double                 DEFAULT 0,
    `channel_fee_price`    bigint(20)             DEFAULT 0,
    `status`               tinyint(4)    NOT NULL,
    `user_ip`              varchar(50)   NOT NULL,
    `user_id`              bigint(20)             DEFAULT NULL,
    `user_type`            tinyint(4)             DEFAULT NULL,
    `expire_time`          timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `success_time`         datetime(0)            DEFAULT CURRENT_TIMESTAMP,
    `notify_time`          datetime(0)            DEFAULT CURRENT_TIMESTAMP,
    `extension_id` bigint(20)             DEFAULT NULL,
    `no`                   varchar(64)   NULL,
    `refund_price`         bigint(20)    NOT NULL,
    `channel_user_id`      varchar(255)           DEFAULT NULL,
    `channel_order_no`     varchar(64)            DEFAULT NULL,
    `creator`              varchar(64)            DEFAULT '',
    `create_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(64)            DEFAULT '',
    `update_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '支付订单';

CREATE TABLE IF NOT EXISTS `pay_order_extension` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `no`           varchar(64)         NOT NULL,
    `order_id`           bigint(20)    NOT NULL,
    `channel_id`         bigint(20)    NOT NULL,
    `channel_code`       varchar(32)   NOT NULL,
    `user_ip`            varchar(50)   NULL     DEFAULT NULL,
    `status`             tinyint(4)    NOT NULL,
    `channel_extras`     varchar(1024) NULL     DEFAULT NULL,
    `channel_error_code`  varchar(64)  NULL,
    `channel_error_msg` varchar(64)    NULL,
    `channel_notify_data` varchar(1024)  NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '支付订单拓展';

CREATE TABLE IF NOT EXISTS `pay_refund` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `no`           varchar(64)         NOT NULL,
    `app_id`             bigint(20)    NOT NULL,
    `channel_id`         bigint(20)    NOT NULL,
    `channel_code`       varchar(32)   NOT NULL,
    `order_id`           bigint(20)    NOT NULL,
    `order_no`           varchar(64)    NOT NULL,
    `merchant_order_id`  varchar(64)   NOT NULL,
    `merchant_refund_id` varchar(64)   NOT NULL,
    `notify_url`         varchar(1024) NOT NULL,
    `status`             tinyint(4)    NOT NULL,
    `pay_price`         bigint(20)    NOT NULL,
    `refund_price`      bigint(20)    NOT NULL,
    `reason`             varchar(256)  NOT NULL,
    `user_ip`            varchar(50)   NULL     DEFAULT NULL,
    `user_id`            bigint(20)    NULL     DEFAULT NULL,
    `user_type`          tinyint(4)    NULL     DEFAULT NULL,
    `channel_order_no`   varchar(64)   NOT NULL,
    `channel_refund_no`  varchar(64)   NULL     DEFAULT NULL,
    `success_time`       datetime(0)   NULL     DEFAULT NULL,
    `channel_error_code` varchar(128)  NULL     DEFAULT NULL,
    `channel_error_msg`  varchar(256)  NULL     DEFAULT NULL,
    `channel_notify_data` varchar(1024)  NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '退款订单';

CREATE TABLE IF NOT EXISTS `pay_notify_task` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `app_id`             bigint(20)    NOT NULL,
    `type`               tinyint(4)    NOT NULL,
    `data_id`           bigint(20)    NOT NULL,
    `merchant_order_id`           varchar(64)    NOT NULL,
    `status`             tinyint(4)    NOT NULL,
    `next_notify_time`       datetime(0)   NULL     DEFAULT NULL,
    `last_execute_time`       datetime(0)   NULL     DEFAULT NULL,
    `notify_times`         int    NOT NULL,
    `max_notify_times`         int    NOT NULL,
    `notify_url`         varchar(1024) NOT NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    `tenant_id`           bigint(20)    NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT = '支付通知任务';

CREATE TABLE IF NOT EXISTS `pay_notify_log` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `task_id`             bigint(20)    NOT NULL,
    `notify_times`         int    NOT NULL,
    `response`         varchar(1024) NOT NULL,
    `status`             tinyint(4)    NOT NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '支付通知日志';

CREATE TABLE IF NOT EXISTS `pay_transfer` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `no`                   varchar(64)   NOT NULL,
    `app_id`               bigint(20)    NOT NULL,
    `channel_id`           bigint(20)    NOT NULL,
    `channel_code`         varchar(32)   NOT NULL,
    `user_id`              bigint(20)    NULL     DEFAULT NULL,
    `user_type`            tinyint(4)    NULL     DEFAULT NULL,
    `merchant_transfer_id` varchar(64)   NOT NULL,
    `price`                bigint(20)    NOT NULL,
    `subject`              varchar(256)  NOT NULL,
    `user_account`         varchar(256)  NOT NULL,
    `user_name`            varchar(64)   NULL     DEFAULT NULL,
    `status`               tinyint(4)    NOT NULL,
    `notify_url`           varchar(1024) NULL     DEFAULT NULL,
    `channel_transfer_no`  varchar(64)   NULL     DEFAULT NULL,
    `success_time`         datetime(0)   NULL     DEFAULT NULL,
    `channel_error_code`   varchar(128)  NULL     DEFAULT NULL,
    `channel_error_msg`    varchar(256)  NULL     DEFAULT NULL,
    `channel_notify_data`  varchar(1024) NULL     DEFAULT NULL,
    `channel_extras`       varchar(1024) NULL     DEFAULT NULL,
    `creator`              varchar(64)   NULL     DEFAULT '',
    `create_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(64)   NULL     DEFAULT '',
    `update_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)        NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT = '转账单';

-- ------------------------------------------------------------------
-- Source: yudao-module-mall/yudao-module-product/src/test/resources/sql/create_tables.sql
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_sku` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `spu_id` bigint NOT NULL COMMENT 'spu编号',
    `properties` varchar(512)  DEFAULT NULL COMMENT '属性数组，JSON 格式',
    `price` int NOT NULL DEFAULT '-1' COMMENT '商品价格，单位：分',
    `market_price` int DEFAULT NULL COMMENT '市场价，单位：分',
    `cost_price` int NOT NULL DEFAULT '-1' COMMENT '成本价，单位： 分',
    `bar_code` varchar(64)  DEFAULT NULL COMMENT 'SKU 的条形码',
    `pic_url` varchar(256)  NOT NULL COMMENT '图片地址',
    `stock` int DEFAULT NULL COMMENT '库存',
    `weight` double DEFAULT NULL COMMENT '商品重量，单位：kg 千克',
    `volume` double DEFAULT NULL COMMENT '商品体积，单位：m^3 平米',
    `sub_commission_first_price` int DEFAULT NULL COMMENT '一级分销的佣金，单位：分',
    `sub_commission_second_price` int DEFAULT NULL COMMENT '二级分销的佣金，单位：分',
    `sales_count` int DEFAULT NULL COMMENT '商品销量',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    PRIMARY KEY(`id`)
) COMMENT '商品sku';

CREATE TABLE IF NOT EXISTS `product_spu` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '商品 SPU 编号，自增',
    `name` varchar(128) NOT NULL COMMENT '商品名称',
    `keyword` varchar(256) NOT NULL COMMENT '关键字',
    `introduction` varchar(256) NOT NULL COMMENT '商品简介',
    `description` text NOT NULL COMMENT '商品详情',
    `bar_code` varchar(64) NOT NULL COMMENT '条形码',
    `category_id` bigint NOT NULL COMMENT '商品分类编号',
    `brand_id` int DEFAULT NULL COMMENT '商品品牌编号',
    `pic_url` varchar(256) NOT NULL COMMENT '商品封面图',
    `slider_pic_urls` varchar(2000)  DEFAULT '' COMMENT '商品轮播图地址\n 数组，以逗号分隔\n 最多上传15张',
    `video_url` varchar(256) DEFAULT NULL COMMENT '商品视频',
    `unit` tinyint NOT NULL COMMENT '单位',
    `sort` int NOT NULL DEFAULT '0' COMMENT '排序字段',
    `status` tinyint NOT NULL COMMENT '商品状态: 0 上架（开启） 1 下架（禁用）-1 回收',
    `spec_type` bit(1) NOT NULL COMMENT '规格类型：0 单规格 1 多规格',
    `price` int NOT NULL DEFAULT '-1' COMMENT '商品价格，单位使用：分',
    `market_price` int NOT NULL COMMENT '市场价，单位使用：分',
    `cost_price` int NOT NULL DEFAULT '-1' COMMENT '成本价，单位： 分',
    `stock` int NOT NULL DEFAULT '0' COMMENT '库存',
    `delivery_template_id` bigint NOT NULL COMMENT '物流配置模板编号',
    `recommend_hot` bit(1) NOT NULL COMMENT '是否热卖推荐: 0 默认 1 热卖',
    `recommend_benefit` bit(1) NOT NULL COMMENT '是否优惠推荐: 0 默认 1 优选',
    `recommend_best` bit(1) NOT NULL COMMENT '是否精品推荐: 0 默认 1 精品',
    `recommend_new` bit(1) NOT NULL COMMENT '是否新品推荐: 0 默认 1 新品',
    `recommend_good` bit(1) NOT NULL COMMENT '是否优品推荐',
    `give_integral` int NOT NULL COMMENT '赠送积分',
    `give_coupon_template_ids` varchar(512)  DEFAULT '' COMMENT '赠送的优惠劵编号的数组',
    `sub_commission_type` bit(1) NOT NULL COMMENT '分销类型',
    `activity_orders` varchar(16) NOT NULL DEFAULT '' COMMENT '活动显示排序0=默认, 1=秒杀，2=砍价，3=拼团',
    `sales_count` int DEFAULT '0' COMMENT '商品销量',
    `virtual_sales_count` int DEFAULT '0' COMMENT '虚拟销量',
    `browse_count` int DEFAULT '0' COMMENT '商品点击量',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    PRIMARY KEY(`id`)
) COMMENT '商品spu';

CREATE TABLE IF NOT EXISTS `product_category` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
    `parent_id` bigint NOT NULL COMMENT '父分类编号',
    `name` varchar(255) NOT NULL COMMENT '分类名称',
    `pic_url` varchar(255) NOT NULL COMMENT '移动端分类图',
    `big_pic_url` varchar(255) DEFAULT NULL COMMENT 'PC 端分类图',
    `sort` int DEFAULT '0' COMMENT '分类排序',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    PRIMARY KEY(`id`)
) COMMENT '商品分类';

CREATE TABLE IF NOT EXISTS `product_brand` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '品牌编号',
    `name` varchar(255) NOT NULL COMMENT '品牌名称',
    `pic_url` varchar(255) NOT NULL COMMENT '品牌图片',
    `sort` int DEFAULT '0' COMMENT '品牌排序',
    `description` varchar(1024) DEFAULT NULL COMMENT '品牌描述',
    `status` tinyint NOT NULL COMMENT '状态',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    PRIMARY KEY(`id`)
) COMMENT '商品品牌';

CREATE TABLE IF NOT EXISTS `product_property` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` varchar(64) DEFAULT NULL COMMENT '规格名称',
    `status` tinyint DEFAULT NULL COMMENT '状态： 0 开启 ，1 禁用',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY(`id`)
) COMMENT '规格名称';

CREATE TABLE IF NOT EXISTS `product_property_value` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `property_id` bigint DEFAULT NULL COMMENT '规格键id',
    `name` varchar(128) DEFAULT NULL COMMENT '规格值名字',
    `status` tinyint DEFAULT NULL COMMENT '状态： 1 开启 ，2 禁用',
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default  '0',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY(`id`)
) COMMENT '规格值';


-- ------------------------------------------------------------------
-- Source: yudao-module-mall/yudao-module-promotion/src/test/resources/sql/create_tables.sql
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `market_activity`
(
    `id`                    bigint(20)  NOT NULL AUTO_INCREMENT,
    `title`                 varchar(50) NOT NULL,
    `activity_type`         tinyint(4)  NOT NULL,
    `status`                tinyint(4)  NOT NULL,
    `start_time`            datetime    NOT NULL,
    `end_time`              datetime    NOT NULL,
    `invalid_time`          datetime,
    `delete_time`           datetime,
    `time_limited_discount` varchar(2000),
    `full_privilege`        varchar(2000),
    `creator`               varchar(64)          DEFAULT '',
    `create_time`           datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`               varchar(64)          DEFAULT '',
    `update_time`           datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`               bit(1)         NOT NULL DEFAULT FALSE,
    `tenant_id`             bigint(20)  NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '促销活动';

CREATE TABLE IF NOT EXISTS `promotion_coupon_template`
(
    `id`                   bigint   NOT NULL AUTO_INCREMENT,
    `name`                 varchar(255)  NOT NULL,
    `status`               int      NOT NULL,
    `total_count`          int      NOT NULL,
    `take_limit_count`     int      NOT NULL,
    `take_type`            int      NOT NULL,
    `use_price`            int      NOT NULL,
    `product_scope`        int      NOT NULL,
    `product_spu_ids`      varchar(255),
    `validity_type`        int      NOT NULL,
    `valid_start_time`     datetime,
    `valid_end_time`       datetime,
    `fixed_start_term`     int,
    `fixed_end_term`       int,
    `discount_type`        int      NOT NULL,
    `discount_percent`     int,
    `discount_price`       int,
    `discount_limit_price` int,
    `take_count`           int      NOT NULL DEFAULT 0,
    `use_count`            int      NOT NULL DEFAULT 0,
    `creator`              varchar(255)           DEFAULT '',
    `create_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(255)           DEFAULT '',
    `update_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '优惠劵模板';

CREATE TABLE IF NOT EXISTS `promotion_coupon`
(
    `id`                   bigint   NOT NULL AUTO_INCREMENT,
    `template_id`          bigint   NOT NULL,
    `name`                 varchar(255)  NOT NULL,
    `status`               int      NOT NULL,
    `user_id`              bigint   NOT NULL,
    `take_type`            int      NOT NULL,
    `useprice`             int      NOT NULL,
    `valid_start_time`     datetime NOT NULL,
    `valid_end_time`       datetime NOT NULL,
    `product_scope`        int      NOT NULL,
    `product_spu_ids`      varchar(255),
    `discount_type`        int      NOT NULL,
    `discount_percent`     int,
    `discount_price`       int,
    `discount_limit_price` int,
    `use_order_id`         bigint,
    `use_time`             datetime,
    `creator`              varchar(255)           DEFAULT '',
    `create_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(255)           DEFAULT '',
    `update_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '优惠劵';

CREATE TABLE IF NOT EXISTS `promotion_reward_activity`
(
    `id`              bigint   NOT NULL AUTO_INCREMENT,
    `name`            varchar(255)  NOT NULL,
    `status`          int      NOT NULL,
    `start_time`      datetime NOT NULL,
    `end_time`        datetime NOT NULL,
    `remark`          varchar(255),
    `condition_type`  int      NOT NULL,
    `product_scope`   int      NOT NULL,
    `product_spu_ids` varchar(255),
    `rules`           varchar(255),
    `creator`         varchar(255)           DEFAULT '',
    `create_time`     datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`         varchar(255)           DEFAULT '',
    `update_time`     datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`         bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '满减送活动';

CREATE TABLE IF NOT EXISTS `promotion_discount_activity`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT,
    `name`        varchar(255)  NOT NULL,
    `status`      int      NOT NULL,
    `start_time`  datetime NOT NULL,
    `end_time`    datetime NOT NULL,
    `remark`      varchar(255),
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '限时折扣活动';

CREATE TABLE IF NOT EXISTS `promotion_seckill_activity`
(
    `id`                 bigint   NOT NULL AUTO_INCREMENT,
    `spu_id`             bigint   NOT NULL,
    `name`               varchar(255)  NOT NULL,
    `status`             int      NOT NULL,
    `remark`             varchar(255),
    `start_time`         varchar(255)  NOT NULL,
    `end_time`           varchar(255)  NOT NULL,
    `sort`               int      NOT NULL,
    `config_ids`         varchar(255)  NOT NULL,
    `order_count`        int      NOT NULL,
    `user_count`         int      NOT NULL,
    `total_price`        int      NOT NULL,
    `total_limit_count`  int,
    `single_limit_count` int,
    `stock`              int,
    `total_stock`        int,
    `creator`            varchar(255)           DEFAULT '',
    `create_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(255)           DEFAULT '',
    `update_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`          bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '秒杀活动';

CREATE TABLE IF NOT EXISTS `promotion_seckill_config`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT,
    `name`        varchar(255)  NOT NULL,
    `start_time`  varchar(255)  NOT NULL,
    `end_time`    varchar(255)  NOT NULL,
    `pic_url`     varchar(255)  NOT NULL,
    `status`      int      NOT NULL,
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`   bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '秒杀时段配置';

CREATE TABLE IF NOT EXISTS `promotion_combination_activity`
(
    `id`                 bigint   NOT NULL AUTO_INCREMENT,
    `name`               varchar(255)  NOT NULL,
    `spu_id`             bigint,
    `total_limit_count`  int      NOT NULL,
    `single_limit_count` int      NOT NULL,
    `start_time`         varchar(255)  NOT NULL,
    `end_time`           varchar(255)  NOT NULL,
    `user_size`          int      NOT NULL,
    `total_num`          int      NOT NULL,
    `success_num`        int      NOT NULL,
    `order_user_count`   int      NOT NULL,
    `virtual_group`      int      NOT NULL,
    `status`             int      NOT NULL,
    `limit_duration`     int      NOT NULL,
    `creator`            varchar(255)           DEFAULT '',
    `create_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(255)           DEFAULT '',
    `update_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`          bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '拼团活动';

CREATE TABLE IF NOT EXISTS `promotion_article_category`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT,
    `name`        varchar(255)  NOT NULL,
    `pic_url`     varchar(255),
    `status`      int      NOT NULL,
    `sort`        int      NOT NULL,
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`   bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '文章分类表';

CREATE TABLE IF NOT EXISTS `promotion_article`
(
    `id`               bigint   NOT NULL AUTO_INCREMENT,
    `category_id`      bigint   NOT NULL,
    `title`            varchar(255)  NOT NULL,
    `author`           varchar(255),
    `pic_url`          varchar(255)  NOT NULL,
    `introduction`     varchar(255),
    `browse_count`     varchar(255),
    `sort`             int      NOT NULL,
    `status`           int      NOT NULL,
    `spu_id`           bigint   NOT NULL,
    `recommend_hot`    bit(1)      NOT NULL,
    `recommend_banner` bit(1)      NOT NULL,
    `content`          varchar(255)  NOT NULL,
    `creator`          varchar(255)           DEFAULT '',
    `create_time`      datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`          varchar(255)           DEFAULT '',
    `update_time`      datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`          bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`        bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '文章管理表';

CREATE TABLE IF NOT EXISTS `promotion_diy_template`
(
    `id`                 bigint   NOT NULL AUTO_INCREMENT,
    `name`               varchar(255)  NOT NULL,
    `used`               bit(1)      NOT NULL,
    `used_time`          varchar(255),
    `remark`             varchar(255),
    `preview_pic_urls`   varchar(255),
    `property`           varchar(255)  NOT NULL,
    `creator`            varchar(255)           DEFAULT '',
    `create_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(255)           DEFAULT '',
    `update_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`          bigint   NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) COMMENT '装修模板';
CREATE TABLE IF NOT EXISTS `promotion_diy_page`
(
    `id`                 bigint   NOT NULL AUTO_INCREMENT,
    `template_id`        bigint   NOT NULL,
    `name`               varchar(255)  NOT NULL,
    `remark`             varchar(255),
    `preview_pic_urls`   varchar(255),
    `property`           varchar(255),
    `creator`            varchar(255)           DEFAULT '',
    `create_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(255)           DEFAULT '',
    `update_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`          bigint   NOT NULL,
    PRIMARY KEY (`id`)
) COMMENT '装修页面';
-- ------------------------------------------------------------------
-- Source: yudao-module-mall/yudao-module-trade/src/test/resources/sql/create_tables.sql
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade_order`
(
    `id`                      bigint   NOT NULL AUTO_INCREMENT,
    `no`                      varchar(255)  NOT NULL,
    `type`                    int      NOT NULL,
    `terminal`                int      NOT NULL,
    `user_id`                 bigint   NOT NULL,
    `user_ip`                 varchar(255)  NOT NULL,
    `user_remark`             varchar(255),
    `status`                  int      NOT NULL,
    `product_count`           int      NOT NULL,
    `cancel_type`             int,
    `remark`                  varchar(255),
    `comment_status`          tinyint(1),
    `brokerage_user_id`       bigint,
    `pay_status`              bit(1)      NOT NULL,
    `pay_time`                datetime,
    `finish_time`             datetime,
    `cancel_time`             datetime,
    `total_price`             int      NULL,
    `order_price`             int      NULL,
    `discount_price`          int      NOT NULL,
    `delivery_price`          int      NOT NULL,
    `adjust_price`            int      NOT NULL,
    `pay_price`               int      NOT NULL,
    `delivery_type`           int      NOT NULL,
    `pay_order_id`            bigint,
    `pay_channel_code`        varchar(255),
    `delivery_template_id`    bigint,
    `logistics_id`            bigint,
    `logistics_no`            varchar(255),
    `delivery_time`           datetime,
    `receive_time`            datetime,
    `receiver_name`           varchar(255)  NOT NULL,
    `receiver_mobile`         varchar(255)  NOT NULL,
    `receiver_area_id`        int      NOT NULL,
    `receiver_post_code`      int,
    `receiver_detail_address` varchar(255)  NOT NULL,
    `pick_up_store_id`        bigint     NULL,
    `pick_up_verify_code`     varchar(255)  NULL,
    `refund_status`           int      NULL,
    `refund_price`            int      NULL,
    `after_sale_status`       int      NULL,
    `coupon_id`               bigint   NOT NULL,
    `coupon_price`            int      NOT NULL,
    `use_point`               int      NULL,
    `point_price`             int      NOT NULL,
    `give_point`              int      NULL,
    `refund_point`            int      NULL,
    `vip_price`               int      NULL,
    `give_coupons_map`        varchar(255)  NULL,
    `seckill_activity_id`     bigint     NULL,
    `bargain_activity_id`     bigint     NULL,
    `bargain_record_id`       bigint     NULL,
    `combination_activity_id` bigint     NULL,
    `combination_head_id`     bigint     NULL,
    `combination_record_id`   bigint     NULL,
    `creator`                 varchar(255)           DEFAULT '',
    `create_time`             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`                 varchar(255)           DEFAULT '',
    `update_time`             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`                 bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易订单表';

CREATE TABLE IF NOT EXISTS `trade_order_item`
(
    `id`                bigint   NOT NULL AUTO_INCREMENT,
    `user_id`           bigint   NOT NULL,
    `order_id`          bigint   NOT NULL,
    `cart_id`           int      NULL,
    `spu_id`            bigint   NOT NULL,
    `spu_name`          varchar(255)  NOT NULL,
    `sku_id`            bigint   NOT NULL,
    `properties`        varchar(255),
    `pic_url`           varchar(255),
    `count`             int      NOT NULL,
    `comment_status`    tinyint(1)  NULL,
    `price`             int      NOT NULL,
    `discount_price`    int      NOT NULL,
    `delivery_price`    int      NULL,
    `adjust_price`      int      NULL,
    `pay_price`         int      NOT NULL,
    `coupon_price`      int      NULL,
    `point_price`       int      NULL,
    `use_point`         int      NULL,
    `give_point`        int      NULL,
    `vip_price`         int      NULL,
    `after_sale_id`     bigint     NULL,
    `after_sale_status` int      NOT NULL,
    `creator`           varchar(255)           DEFAULT '',
    `create_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`           varchar(255)           DEFAULT '',
    `update_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`           bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易订单明细表';

CREATE TABLE IF NOT EXISTS `trade_after_sale`
(
    `id`             bigint   NOT NULL AUTO_INCREMENT,
    `no`             varchar(255)  NOT NULL,
    `status`         int      NOT NULL,
    `type`           int      NOT NULL,
    `way`            int      NOT NULL,
    `user_id`        bigint   NOT NULL,
    `apply_reason`   varchar(255)  NOT NULL,
    `apply_description` varchar(255),
    `apply_pic_urls` varchar(255),
    `order_id`       bigint   NOT NULL,
    `order_no`       varchar(255)  NOT NULL,
    `order_item_id`  bigint   NOT NULL,
    `spu_id`         bigint   NOT NULL,
    `spu_name`       varchar(255)  NOT NULL,
    `sku_id`         bigint   NOT NULL,
    `properties`     varchar(255),
    `pic_url`        varchar(255),
    `count`          int      NOT NULL,
    `audit_time`     varchar(255),
    `audit_user_id`  bigint,
    `audit_reason`   varchar(255),
    `refund_price`   int      NOT NULL,
    `pay_refund_id`  bigint,
    `refund_time`    varchar(255),
    `logistics_id`   bigint,
    `logistics_no`   varchar(255),
    `delivery_time`  varchar(255),
    `receive_time`   varchar(255),
    `receive_reason` varchar(255),
    `creator`        varchar(255)           DEFAULT '',
    `create_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`        varchar(255)           DEFAULT '',
    `update_time`    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`        bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易售后表';

CREATE TABLE IF NOT EXISTS `trade_after_sale_log`
(
    `id`            bigint   NOT NULL AUTO_INCREMENT,
    `user_id`       bigint   NOT NULL,
    `user_type`     int      NOT NULL,
    `after_sale_id` bigint   NOT NULL,
    `order_id`      bigint   NOT NULL,
    `order_item_id` bigint   NOT NULL,
    `before_status` int,
    `after_status`  int      NOT NULL,
    `content`       varchar(255)  NOT NULL,
    `creator`       varchar(255)           DEFAULT '',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`       varchar(255)           DEFAULT '',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`       bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '交易售后日志';

CREATE TABLE IF NOT EXISTS `trade_brokerage_user`
(
    `id`                bigint   NOT NULL AUTO_INCREMENT,
    `bind_user_id`      bigint   NOT NULL,
    `bind_user_time`    varchar(255),
    `brokerage_enabled` bit(1)      NOT NULL,
    `brokerage_time`    varchar(255),
    `price`             int      NOT NULL,
    `frozen_price`      int      NOT NULL,
    `creator`           varchar(255)           DEFAULT '',
    `create_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`           varchar(255)           DEFAULT '',
    `update_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`           bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id`         bigint   NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`)
) COMMENT '分销用户';
CREATE TABLE IF NOT EXISTS `trade_brokerage_record`
(
    `id`            int      NOT NULL AUTO_INCREMENT,
    `user_id`       bigint   NOT NULL,
    `biz_id`        varchar(255)  NOT NULL,
    `biz_type`      varchar(255)  NOT NULL,
    `title`         varchar(255)  NOT NULL,
    `price`         int      NOT NULL,
    `total_price`   int      NOT NULL,
    `description`   varchar(255)  NOT NULL,
    `status`        varchar(255)  NOT NULL,
    `frozen_days`   int      NOT NULL,
    `unfreeze_time` varchar(255),
    `creator`       varchar(255)           DEFAULT '',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`       varchar(255)           DEFAULT '',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`       bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '佣金记录';
CREATE TABLE IF NOT EXISTS `trade_brokerage_withdraw`
(
    `id`                  int      NOT NULL AUTO_INCREMENT,
    `user_id`             bigint   NOT NULL,
    `price`               int      NOT NULL,
    `fee_price`           int      NOT NULL,
    `total_price`         int      NOT NULL,
    `type`                varchar(255)  NOT NULL,
    `name`                varchar(255),
    `account_no`          varchar(255),
    `bank_name`           varchar(255),
    `bank_address`        varchar(255),
    `account_qr_code_url` varchar(255),
    `status`              varchar(255)  NOT NULL,
    `audit_reason`        varchar(255),
    `audit_time`          varchar(255),
    `remark`              varchar(255),
    `creator`             varchar(255)           DEFAULT '',
    `create_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`             varchar(255)           DEFAULT '',
    `update_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`             bit(1)      NOT NULL DEFAULT FALSE,
    `tenant_id` bigint not null default '0',
    PRIMARY KEY (`id`)
) COMMENT '佣金提现';

CREATE TABLE IF NOT EXISTS `trade_delivery_express`
(
    `id`          int      NOT NULL AUTO_INCREMENT,
    `code`        varchar(255)  NULL,
    `name`        varchar(255),
    `logo`        varchar(255)  NULL,
    `sort`        int      NOT NULL,
    `status`      int      NOT NULL,
    `creator`     varchar(255)           DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`     varchar(255)           DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`     bit(1)      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
) COMMENT '佣金提现';
SET FOREIGN_KEY_CHECKS = 1;
